CREATE TABLE news (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    authorid INTEGER NOT NULL REFERENCES users(id),
    submitted TIMESTAMP NOT NULL,
    slug VARCHAR(80) NOT NULL UNIQUE,
    enabled BOOLEAN DEFAULT TRUE
);
